### ISSUE TITLE
Don't return file content for HEAD requests in ServeFile, ServeDir

### ISSUE THREAD

**Issue by jplatte** [tower-rs/tower-http#113]
As discussed in tokio-rs/axum#84, `ServeFile` and `ServeDir` could be improved re. handling of HEAD requests. Responses to HEAD requests should be identical to the corresponding GETs response, but without a body.

The implementation should probably use `fs::metadata` instead of opening the file to fulfill HEAD requests more efficiently.

**Comment by jplatte** [comment]
I wonder whether it makes sense to even support all methods by default. Just ignoring `POST` & `PUT` bodies and returning the file contents on `TRACE` / `DELETE` / `OPTIONS` seems kind of weird. This probably applies to other services in tower-http as well.

**Comment by davidpdrsn** [comment]
Fixing this will unfortunately be a breaking change since `ServeFile` implements `Service` for any type `R` rather than `Service<Request<ReqBody>>`.

**Comment by davidpdrsn** [comment]
> I wonder whether it makes sense to even support all methods by default. Just ignoring POST & PUT bodies and returning the file contents on TRACE / DELETE / OPTIONS seems kind of weird. This probably applies to other services in tower-http as well.

I agree. Method handling could be improved for `ServeDir` and `ServeFile`. Off the top of my head I don't any other services have similar issues.

**Comment by jplatte** [comment]
Oh I see, there's only one more service currently which is the redirect one (which probably *should* work the same regardless of HTTP method).

**Comment by Nehliin** [comment]
https://github.com/tower-rs/tower-http/pull/156 Have the same required breaking change since it needs to inspect the `Accepted-Encoding` headers so I could pick this up after that PR is reviewed
