### ISSUE TITLE
Make `AuthorizeRequest::authorize` return a Future

### ISSUE THREAD

**Issue by hamza1311** [tower-rs/tower-http#116]
## Feature Request

Make [`AuthorizeRequest::authorize`](https://docs.rs/tower-http/0.1.1/tower_http/auth/require_authorization/trait.AuthorizeRequest.html#tymethod.authorize) return a Future.

### Motivation

 In it's current state, it is impossible to make async (database) calls in `AuthorizeRequest::authorize`. Such calls are are very important in a real-world application where user data is stored in a database.

### Proposal

Make the given function `async`. This does, however, comes with the downsides of making a trait function `async`.

### Alternatives

Add an async version of the function/trait, similar to [`AsyncFilter`](https://docs.rs/tower/0.4.8/tower/filter/struct.AsyncFilter.html).

**Comment by hawkw** [comment]
> ### Proposal
>
> Make the given function `async`. This does, however, comes with the downsides of making a trait function `async`.
>
> ### Alternatives
> 
> Add an async version of the function/trait, similar to [`AsyncFilter`](https://docs.rs/tower/0.4.8/tower/filter/struct.AsyncFilter.html).

I think the alternative suggestion is the correct thing to do here, for two reasons:
1. Changing the existing `AuthorizeRequest` to be async is a breaking change, but adding a new trait is not breaking
2. In some cases, it's not necessary to do something asynchronous to authorize a request; when that's the case, it would be nice to avoid the overhead of having to return a future. We probably want to have a new `AuthorizeAsync` trait (or something similar).

**Comment by hamza1311** [comment]
How will the `RequireAuthorization` struct accept that? I imagine it would using an enum (PS: I didn't look at implementation of `AsyncFilter`)

I'd be happy to PR this in a couple of days
