### ISSUE TITLE
Have `ServeDir` and `ServeFile` serve precompressed files

### ISSUE THREAD

**Issue by paolobarbolini** [tower-rs/tower-http#120]
### Motivation

Currently tower-http has `tower_http::services::{ServeDir, ServeFile}` for serving files from the filesystem and `tower_http::compression::Compression` for compressing responses on the fly, but no way of serving precompressed files.

Since our service is built into a docker container we could precompress static assets at build time and have the server use the precompressed versions.

### Proposal

Add an option to both `ServeDir` and `ServeFile` to enable serving precompressed files based on the client's `Accept-Encoding` header.
This would allow us to gzip and brotli compress at the maximum compression level without incurring in the runtime cost of recompressing a file multiple times for every new request that comes in.

### Alternatives

Have static files be served by nginx, which has the [ngx_http_gzip_static_module module](http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html) for serving precompressed files.

**Comment by davidpdrsn** [comment]
What should happen if the file is requested by a client that doesn't support the compression that was used?

**Comment by paolobarbolini** [comment]
> What should happen if the file is requested by a client that doesn't support the compression that was used?

The uncompressed version of the file would still need to be present, so that's the version that would be served.

The way the ngx_http_gzip_static_module module works is that you have both the uncompressed and the compressed versions of the files and the module chooses the best option for each client.

**Comment by davidpdrsn** [comment]
It would be neat if this was something `Compression` could handle in a more general way. Not sure how that would work though.

I think this is a good thing to support regardless. Pretty much the same thing was requested for axum here https://github.com/tokio-rs/axum/issues/66

**Comment by paolobarbolini** [comment]
> It would be neat if this was something `Compression` could handle in a more general way. Not sure how that would work though.

Thinking a bit about this idea I wouldn't want to have to compile the compression crates just to support serving precompressed files, so it would have to live under a separate crate feature.
