### ISSUE TITLE
more configurable grpc tracer

### ISSUE THREAD

**Issue by tamuhey** [tower-rs/tower-http#126]
## Feature Request

`GrpcErrorsAsFailures` classifies all non-zero status responses as `Failure`. 
However, there are times when I want to classify `InvalidArgument` status as a non-failure because it is a user error.

### Alternatives

Currently, I copy & paste the `GrpcErrorsAsFailures` code and modify the classification flow.

**Comment by MarcusGrass** [comment]
I think I'll take a stab at this, trying not to create a monster
