### ISSUE TITLE
Layer for set multiple headers

### ISSUE THREAD

**Issue by Z4RX** [tower-rs/tower-http#134]
### Motivation

`SetResponseHeaderLayer` is too verbose for setting multiple headers. For example utilities like [helmet](SetResponseHeaderLayer) set lots of headers (helmet do it for security purposes. So possibility of setting group of headers in one place instead of doing it one-by-one will make code more readable and will improve user experience.

In addition this feature already exists in `warp`, `rocket` and `actix-web`.

### Drawbacks
It shouldn't have drawbacks or require breaking changes.

**Comment by MarcusGrass** [comment]
@davidpdrsn I'm thinking about tackling this.
Do you think we should create a new middleware or expand the old one to handle many headers?
In either case, maybe the most ergonomic would be to be able to pass a collection of headers (name, make, insertmode) in a method. I'm thinking something like a builder which contains a vec of headers and have that builder contain the methods for constructing an overriding/appending/if_not_present/fully-specified header then supplying that to the layer

**Comment by davidpdrsn** [comment]
I haven't thought much about this yet but feel free to pick it up 😊

Some very immediate off the top of my head thoughts:
- Breaking changes to the existing middleware are fine but we shouldn't just break it for the hell of it
- If we go with a single middleware it should ideally be easy and performant to add a single header. For example using a `Vec` with one header isn't great since you have to allocate a `Vec` to contain a header that is reference counter. Would be neat if we could avoid that somehow.
- If creating a totally separate middleware is easier (both for us and the users) then thats fine.

**Comment by MarcusGrass** [comment]
After coming up with a really messy solution [here](https://github.com/MarcusGrass/tower-http/tree/set_multiple_response_headers) that might not even solve the original problem, me and @davidpdrsn spoke about what is really needed in this layer.
Actix has a default-headers middleware that lets you specify headers statically. It's pretty simple to implement without it getting messy, but is that what you're looking for?
Warp does have [with_headers](https://docs.rs/warp/0.3.2/warp/reply/fn.with_header.html) but that doesn't quite look like a middleware, if what you're after is being able to set a bunch of headers while looking at a request/response then `MapResponse`(or `MapRequest`) might be what you're after, an implementation could look like this: 
```
#[tokio::test]
  async fn dynamically_set_headers() {
      let svc = ServiceBuilder::new()
          .layer(MapResponseLayer::new(|mut res: Response<()>| {
              let dynamic_headers = produce_headers(&mut res);
              let mut headers = res.headers_mut();
              for (name, value) in dynamic_headers {
                  headers.insert(name, value);
              }
              res
          }))
          .service(service_fn(|req: ()| async move {
              Ok::<_, Infallible>(Response::new(()))
          }));

      let res = svc
          .oneshot(())
          .await
          .unwrap();

      assert_eq!(res.headers().get("my-header-one").unwrap(), "1");
      assert_eq!(res.headers().get("my-header-two").unwrap(), "2");
  }

  fn produce_headers(_res: &mut Response<()>) -> Vec<(HeaderName, HeaderValue)> {
      let mut some_outside_source_value = 1;
      let one = (HeaderName::from_static("my-header-one"), HeaderValue::from(some_outside_source_value));
      some_outside_source_value += 1;
      let two = (HeaderName::from_static("my-header-two"), HeaderValue::from(some_outside_source_value));
      vec![one, two]
  }
```
@Z4RX Does that apply to your use case, if not could you more closely describe what you're trying to do?

**Comment by Z4RX** [comment]
Thx, I d like to set a bunch of headers and your solution using `MapResponse` is perfect! So I think that this issue should be closed now.
