### ISSUE TITLE
Compression layer recompresses responses

### ISSUE THREAD

**Issue by NeoLegends** [tower-rs/tower-http#138]
### Version

v0.1.1

### Description

If a layer below the compression layer returns a response whose body is already compressed, the compression-layer will happily re-compress the already compressed bytes, because it does not check the `Content-Encoding` before applying its body transformation.

https://github.com/tower-rs/tower-http/blob/36157ce3ed7cbf30d2c8016ec8054b703308c585/tower-http/src/compression/future.rs#L34-L67

This behavior is fine, if the content that passes through the layer is known to never be compressed already. In a complex application where the data comes from multiple sources, this might not always be the case. Therefore, the layer should probably check whether there already is a `Content-Encoding` on the response, and not apply any further transformations in this case. This would allow using the compression layer as a kind of "catch-all", at the outer edge of the layer stack.

If you agree I'm happy to send a PR 👍. I'd probably integrate this check into `supports_transparent_compression`.

**Comment by davidpdrsn** [comment]
Yes I think that makes sense 👍

**Comment by NeoLegends** [comment]
Onto the PR then!

Thanks for the quick response!
