### ISSUE TITLE
Only compress responses above a certain size

### ISSUE THREAD

**Issue by NeoLegends** [tower-rs/tower-http#139]
### Motivation

This is something I've seen in other web servers, where compression is only turned on for responses of e. g. `>= 1kB`. In particular, there's no use compressing an empty response.

### Proposal

In the compression layer, check the body's `size_hint()`, and do not compress if there is an exact size hint less than a configured value.

I'd say if the size hint is not exact we default to compressing responses in any case.

### Alternatives

Don't care and keep the current behavior.

**Comment by davidpdrsn** [comment]
I think that would be fine to support. Whether 1k is a good default I'm not sure of, but as long as long as its configurable I think its fine. Should also be clearly documented.
