### ISSUE TITLE
CompressionLayer should perhaps check response's MIME type

### ISSUE THREAD

**Issue by shamblesides** [tower-rs/tower-http#146]
### Version

0.1.1

### Platform

Linux 5.4.0-84-generic #94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Description

It seems like the CompressionLayer compresses all responses, including images, which do not need to be compressed. When I put a CompressionLayer in front of ServeDir for example, I would expect that only text files should be compressed.

**Comment by davidpdrsn** [comment]
Makes sense!

Being able to add a predicate that takes the `http::response::Parts` from the inner service's response and returns whether or not it should be compressed would probably work fine.
