### ISSUE TITLE
Feature request: Customize not-found page for ServeDir

### ISSUE THREAD

**Issue by jplatte** [tower-rs/tower-http#149]
### Motivation

I would like to show a custom 404 not-found page when `ServeDir` can't find a file.

### Proposal

Allow users to customize what happens when a file isn't found. Maybe by making `ServeDir` generic (and putting the constructor on `ServeDir<DefaultNotFoundSvc>`) and adding `ServeDir::<T>::not_found(self, svc: S) -> ServeDir<S>`.

### Alternatives

I first thought about having `ServeDir` return some special error that can be caught higher up and handled separately, but if I understood https://github.com/tokio-rs/axum/issues/257#issuecomment-904775587 correctly, this is not possible.

**Comment by davidpdrsn** [comment]
I feel [`ServiceExt::and_then`](https://docs.rs/tower/0.4.10/tower/trait.ServiceExt.html#method.and_then), and checking the responses status code, is a decent way of handling this since `ServeDir` only returns 404 if it cannot find the file.

**Comment by jplatte** [comment]
I think the discoverability of that wouldn't be _great_, but if the docs were to mention that possibility, that would certainly be much better than the current state of affairs.

**Comment by davidpdrsn** [comment]
Adding it to the docs would be easy. Added it to the 0.1.2 milestone as its a quick fix.
