### ISSUE TITLE
Use `http::request::Parts` instead of `Request<B>` in methods that produce things from requests

### ISSUE THREAD

**Issue by davidpdrsn** [tower-rs/tower-http#154]
We have a couple of methods that look something like this

```rust
fn make_thing<B>(&mut self, request: &Request<B>) -> Thing
```

Such as [`MakeClassifier`](https://docs.rs/tower-http/0.1.1/tower_http/classify/trait.MakeClassifier.html) and [`MakeSpan`](https://docs.rs/tower-http/0.1.1/tower_http/trace/trait.MakeSpan.html).

I've been thinking if it would make sense to change those methods to

```rust
fn make_thing(&mut self, parts: &http::request::Parts) -> Thing
```

This should in theory make rust's type inference better since there is one less generic param. It would also just be simpler overall to understand I think. Users cannot do anything with the request body anyway since there no trait bounds on it, they only have a shared reference to the request, and the functions aren't async.

Thoughts @hawkw @LucioFranco @olix0r?

**Comment by olix0r** [comment]
@davidpdrsn I agree with the intent, but I think this is going to be a bit cumbersome given the current `http::Request` API. Specifically, we only have [`Request::into_parts`](https://docs.rs/http/0.2.5/http/request/struct.Request.html#method.into_parts) which requires fully decomposing the request. It would be a lot more natural if we had a `Request::parts() -> &Parts`...

**Comment by davidpdrsn** [comment]
Yep would require using `into_parts `and `from_parts` inside the middleware. Users shouldn't have to worry about that though I think.

You're right that being able to borrow the parts would make it more convenient.

**Comment by olix0r** [comment]
One thing to consider (from hyperium/http#511) is that switching to `&Parts` requires that the caller has ownership of the request. If you only have a `&http::Request<B>` reference, you can't produce a `&Parts`. So, `&Parts` may be suitable in very specific cases but is probably not the best general pattern to pursue, as it has some unexpected side-effects on composability.

**Comment by davidpdrsn** [comment]
Hm yeah thats a valid point 😕

I think given the concerns I'll be conservative and close this for now. Lets just keep things as they are.
