### ISSUE TITLE
More clearly document features for {de}compression algorithms also must be enabled

### ISSUE THREAD

**Issue by davidpdrsn** [tower-rs/tower-http#165]
The API docs currently make it seem like `compression` (or `decompression`) is the only feature you need to enable it. However you _also_ need to enable one of the algorithms such as `compression-gzip`. The docs should somehow make this more clear.

I'm thinking something like this might do it

```
#[cfg(any(
  feature = "compression-gzip",
  feature = "compression-deflate",
  feature = "compression-brotli",
))]
#[cfg_attr(docsrs, doc(cfg(any(
  feature = "compression-gzip",
  feature = "compression-deflate",
  feature = "compression-brotli",
))))]
```

as hairy as it might be.

**Comment by Nehliin** [comment]
Could we simply remove the `compression` and `decompression` and only have the specific ones + the `*-full`? The compression` and `decompression` also became quite confusing as a developer when trying to change things touching compression

**Comment by davidpdrsn** [comment]
Yep we could do that. Makes sense I think.
