### ISSUE TITLE
Document tower-http's MSRV in the readme

### ISSUE THREAD

**Issue by davidpdrsn** [tower-rs/tower-http#185]
tower-http's MSRV (minimum supported rust version) is [currently 1.51](https://github.com/tower-rs/tower-http/blob/master/.github/workflows/CI.yml#L84) however we don't advertise that in the readme.

I think we should add a section similar to what [axum's readme has](https://github.com/tokio-rs/axum#minimum-supported-rust-version):

![image](https://user-images.githubusercontent.com/718941/142865384-b3c4f255-b662-4fa6-ba8a-b5aabed3911d.png)

We've agreed not to bump our MSRV for 0.2 so should keep it at 1.51. There is some debate about whether bumping MSRV requires a major semver release, however I believe serde did so while remaining 1.x. So if someday we have a good reason to bump our MSRV doing so in a minor version should be fine.

**Comment by hawkw** [comment]
We should probably also add `rust = "1.51"` to the `Cargo.toml` (see https://rust-lang.github.io/rfcs/2495-min-rust-version.html)

**Comment by davidpdrsn** [comment]
Oh I was not aware of that! Yes sounds like we should do that. I guess we should do it for tower itself as well then.

**Comment by Nehliin** [comment]
fixed in #188
