### ISSUE TITLE
Tell `AuthorizeRequest::unauthorized_response` why the request could not be authorized

### ISSUE THREAD

**Issue by hamza1311** [tower-rs/tower-http#190]
### Motivation

The current authorization services returns an `Option` ([see docs](https://docs.rs/tower-http/0.1.2/tower_http/auth/trait.AsyncAuthorizeRequest.html) for `AsyncAuthorizeRequest`). This works but has one major flaw: there is no way to tell why authorization failed. One use case where this is needed is determining what status code to send. 401 is sent if no `Authorization` header is present and 403 is sent in case of (say) an invalid/expired token.

### Proposal

Replace the `Option` with a `Result`. That way, we can inform `{Async}AuthorizeRequest::unauthorized_response` why the request could not be authorized so it can respond appropriately.

This does force the user to handle the error case but that is inline with how Rust handles errors.

### Alternatives

- Use request extensions to figure out what went wrong
  This is janky and error prone. Using `Result` is a much better way.

**Comment by davidpdrsn** [comment]
Changing it to return a Result makes sense to me. Think we should look into this for 0.2.

However, looking at the trait now I'm wondering if it could be simplified somehow. Maybe having a single method that returns an enum of some kind could be easier. Might be worth considering a different design altogether actually 🤔 Just a thought.
