### ISSUE TITLE
Partial Content not working on Firefox and Chrome

### ISSUE THREAD

**Issue by adumbidiot** [tower-rs/tower-http#197]
### Version
`tower-http v0.2.0`

### Platform
`Windows 10 64 bit`

### Description
I was trying to stream a video using the `ServeDir` service, but both Chrome and Firefox were unable to view the video. I'm fairly certain that the `Content-Length` header is being set incorrectly. The following is a sample of some of the response headers I got in Firefox while testing:
![image](https://user-images.githubusercontent.com/26289915/147805167-ea328c2a-8575-49c0-9ea3-84c923693d06.png)

I believe that the content-length header should reflect the message length, not the file length as per the [documentation on mdn](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length). I also made a branch that fixes this issue and seems to allow me to stream the video without issue:  https://github.com/adumbidiot/tower-http/tree/partial-content-quickfix

**Comment by davidpdrsn** [comment]
Thanks for the report! I don't think this should be hard to fix so people are welcome to submit PRs 😊 A test for this would also be good.

**Comment by adumbidiot** [comment]
Fixed with #228
