### ISSUE TITLE
make_span_with use?

### ISSUE THREAD

**Issue by inevity** [tower-rs/tower-http#202]
## Bug Report
make_span_with just create a span .  
we use it record a field from span. and in some callback, such onrequest, we can span.enter and do somethings. 
But we cannot enter the span for the whole req.  Tracing print req enter /req end log once we instrumentation the request func or  call span.enter.

**Comment by davidpdrsn** [comment]
I don't understand what you mean.

The span is entered for the whole duration of the request, [here](https://github.com/tower-rs/tower-http/blob/master/tower-http/src/) in the middleware and [here](https://github.com/tower-rs/tower-http/blob/master/tower-http/src/trace/future.rs) in the future.

**Comment by inevity** [comment]
I mean once enable tracelayer,  cannot found log like the tracing::instrument show,
such as [FUNCNAME ---START] logline and [FUNCNAME ---END] logline, just found the onrequest etc callback log.

**Comment by davidpdrsn** [comment]
Not sure I understand but `#[tracing::instrument]` doesn't create any events - it just creates a span. If you actually want to see the span in your terminal you have to log some events with `tracing::info!()` or enable [span events](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/struct.SubscriberBuilder.html#method.with_span_events).

**Comment by inevity** [comment]
> it just creates a span.

And should  log the span , see [span!(Level::INFO, "my_span", answer = 42);](https://docs.rs/tracing/latest/tracing/span/index.html)

**Comment by davidpdrsn** [comment]
Creating a span doesn't produce any output. It is only when you create events that the spans are shown, if you're using the default tracing-subscriber.

I'm gonna close this issue for now. If you have more questions about tracing would encourage you to ask in `#tracing` in the [tokio discord](https://discord.gg/tokio).
