### ISSUE TITLE
Please consider serving directories embedded in Rust binary

### ISSUE THREAD

**Issue by finnbear** [tower-rs/tower-http#229]
### Motivation

Embedding a small single-page-app in a Rust server binary makes deployment very easy, as it eliminates the need to deploy multiple static files, and eliminates the failure modes of static files being out of sync and file-system errors.

### Proposal

Add `ServeStaticDir` which acts like `ServeDir`, except that its constructor takes an included directory (`Dir`, via [include_dir](https://docs.rs/include_dir/latest/include_dir/)::`include_dir!`)

This functionality could be behind a feature flag if desired, although `include_dir` isn't a heavy crate, especially when its macro isn't invoked.

### Alternatives

Make this an addon to `ServeDir`. This would have the benefit of reducing code duplication (such as the excellent support for precompressed files), but would add (too much, in my view) complexity.

Doing nothing is always an alternative.

### See Also

Here's the same idea, implemented for `actix-web`: https://github.com/john01dav/actix-plus/tree/master/actix-plus-static-files

**Comment by davidpdrsn** [comment]
I know there are crates out there that can do that. I cannot remember any of them now though but people have brought them up before.

I think this is out of scope for tower-http.

**Comment by davidpdrsn** [comment]
Found one https://crates.io/crates/rust-embed

**Comment by finnbear** [comment]
> Found one https://crates.io/crates/rust-embed

Thanks for the quick response and crate suggestion! I took a look at that one, and while it has an axum example (the framework I plan to use), it seems as though it is HTTP-obvlivious in the sense that it doesn't handle ETAGs, caching, content negotiation, (pre)compression, 404 etc. (the things `ServeDir` excels at). The user is expected to provide an HTTP interface, such as https://github.com/pyros2097/rust-embed/blob/74a3e07c1ad968c9bfc914330710bd37e633f604/examples/axum.rs#L61-L71

> I know there are crates out there that can do that. I cannot remember any of them now though but people have brought them up before.

Maybe there is another crate with better HTTP support. I will do some more research, but it can be hard to formulate a good search query because "static files" usually turns up results for `ServeDir`-like implementations that rely on the filesystem.

Assuming there is no such crate, I think there is room for improvement in the ecosystem.

**Comment by davidpdrsn** [comment]
> it seems as though it is HTTP-obvlivious in the sense that it doesn't handle ETAGs, caching, content negotiation, (pre)compression, 404 etc. (the things ServeDir excels at)

Hm thats a good point 🤔 

> Assuming there is no such crate, I think there is room for improvement in the ecosystem.

You should write one 😅 I still don't think its right for tower-http to contain a macro crate like this.
