### ISSUE TITLE
Propagate W3C Trace Context

### ISSUE THREAD

**Issue by jakelee8** [tower-rs/tower-http#238]
### Motivation

Propagate W3C Trace Context to connect traces between service calls.

### Proposal

Not sure what the best way would be to implement this. Could it be implemented by adding a `propagate(true)` method to `DefaultMakeSpan` or wrapping it like the following `PropagatingSpan` workaround?

```
use hyper::{HeaderMap, Request};
use opentelemetry::propagation::Extractor;
use tower_http::trace::{DefaultMakeSpan, MakeSpan};
use tracing::Span;

impl PropagatingSpan {
     pub fn new() -> Self {
         Self {
             inner: DefaultMakeSpan::new(),
         }
     }
 }

 impl<B> MakeSpan<B> for PropagatingSpan {
     fn make_span(&mut self, request: &Request<B>) -> Span {
         let parent_context = opentelemetry::global::get_text_map_propagator(|propagator| {
             propagator.extract(&RequestHeaderCarrier::new(request.headers()))
         });
         let _guard = parent_context.attach();
         self.inner.make_span(request)
     }
 }

 struct RequestHeaderCarrier<'a> {
     headers: &'a HeaderMap,
 }

 impl<'a> RequestHeaderCarrier<'a> {
     fn new(headers: &'a HeaderMap) -> Self {
         RequestHeaderCarrier { headers }
     }
 }

 impl<'a> Extractor for RequestHeaderCarrier<'a> {
     fn get(&self, key: &str) -> Option<&str> {
         self.headers.get(key).and_then(|v| v.to_str().ok())
     }

     fn keys(&self) -> Vec<&str> {
         self.headers.keys().map(|h| h.as_str()).collect()
     }
 }
```

### Alternatives

* Add `DefaultMakeSpan::propagate(true)` method with the `opentelemetry` feature flag
* Add `PropagatingSpan` wrapper - not as clean as adding a method

**Comment by davidpdrsn** [comment]
Sorry but we wont be adding opentelemetry stuff to `Trace`. It should remain flexible such that users can add support for these things without us having to build things into tower-http.

Implementing your own `MakeSpan` sounds like a good place to start.

I'll close this issue but feel free to ask follow up questions.

**Comment by jakelee8** [comment]
Sounds good, I was thinking the same. Thank you for the feedback!
