### ISSUE TITLE
Release check list

### ISSUE THREAD

**Issue by LucioFranco** [tower-rs/tower-http#24]
- [x] Release `http-connection`
- [x] Release `tower-http-util`
- [x] Release `tower-hyper`
- [x] Release `tower-request-modifier`
- [ ] Release `tower-http`

cc @seanmonstar @carllerche

**Comment by carllerche** [comment]
Refs: https://github.com/hyperium/http-connection/issues/3

**Comment by andygrove** [comment]
@carllerche @LucioFranco I was wondering if there is any update on this? It looks like the other crates were published recently.

(for context, I am using tower-grpc from https://github.com/andygrove/ballista)

**Comment by LucioFranco** [comment]
@andygrove hi! `http-connection` and `tower-http-util` are both releasedon crates.io. (I've updated the issue). Looking at your cargo.toml file looks like you only need `tower-request-modifier`. I think this crate actually is totally fine to release right now. As for overall status about tower, we have been focusing heavily on bringing tokio/tower/hyper to std::future::Future so a lot of focus has gone into that instead of finishing up tower-http stuff.

If there is anything you need released besides that I'm happy to help.

**Comment by andygrove** [comment]
Yes, it's really just `tower-request-modifier` that I need right now, then I can start publishing my crate. Thanks!

**Comment by LucioFranco** [comment]
@andygrove Here you go https://crates.io/crates/tower-request-modifier let us know if there are any other things missing. Thanks.

**Comment by andygrove** [comment]
That's awesome! Thanks!!
