### ISSUE TITLE
Add special support for single-page applications which does its own routing

### ISSUE THREAD

**Issue by udoprog** [tower-rs/tower-http#240]
### Motivation

It's fairly common for single page applications to require that all routes which do not match a known file be routed to a single entrypoint (i.e. `index.html`) and then allow it to perform its own routing. So if we go to `/awesome/path` that would be routed to the same entrypoint because `/awesome/path` is not a file being served.

This is hard to implement correctly using `ServeDir`. You could do something like this:

```rust
ServiceBuilder::new()
        .and_then(
            |response: Response<ServeFileSystemResponseBody>| async move {
                let response = if response.status() == StatusCode::NOT_FOUND {
                    match fs::read(&index_html).await {
                        Ok(bytes) => Response::builder()
                            .status(StatusCode::OK)
                            .body(Full::from(bytes).map_err(|err| match err {}).boxed())?,
                        Err(e) if e.kind() == io::ErrorKind::NotFound => {
                            Response::builder().status(StatusCode::NOT_FOUND).body(Empty::new().map_err(|err| match err {}).boxed())?
                        }
                        Err(e) => return Err(Error::from(e)),
                    }
                } else {
                    response.map(|body| body.boxed())
                };

                Ok::<_, Error>(response)
            },
        )
        .service(
            ServeDir::new(root.join("..").join("web").join("dist"))
                .append_index_html_on_directories(false),
        )
```

This however lacks all the request plumbing which is done by `ServeDir`, such as dealing with accept encoding and minor internal path rewrites.

### Proposal / Alternatives

Introduce some way to make it easier to compose a solution that can both leverage the plumbing of `ServeDir` and allow for falling back in case a file is missing and rewrite the request to a different path.

It's made somewhat complicated, because we won't know if the file is available until we try to read it well into the response future at which point we don't have access to the `ServeDir` instance that constructed it.

Unfortunately I don't have a concrete proposal for this since I'm fairly new to both tower and axum.

**Comment by davidpdrsn** [comment]
In axum-extra we recently added [`SpaRouter`](https://docs.rs/axum-extra/latest/axum_extra/routing/struct.SpaRouter.html) to address this.

I decided to put it in axum, rather than tower-http, because it need more complex routing than whats possible with tower-http (such as [`Router::fallback`](https://docs.rs/axum/latest/axum/routing/struct.Router.html#method.fallback))

@udoprog does this address you use case?

**Comment by udoprog** [comment]
Thanks!

Unfortunately I don't think `SpaRouter` cuts it. You can't nest it on `/`:

```rust
let spa = axum_extra::routing::SpaRouter::new("/", path);

let app = Router::new()
    .merge(span)
    /* other routes */
```

```
thread 'main' panicked at 'Invalid route: insertion failed due to conflict with previously registered route: *other route*. Note that `nest("/", _)` conflicts with all routes. Use `Router::fallback` instead'.
```

Without this, I don't think you can route other static assets correctly without having to put them in special nested path. And most frameworks that build single-page applications make the standard assumption that generated assets are fetchable alongside the index file that uses them, typically at the root. For example, here's the output from my currently fairly standard [Trunk](https://trunkrs.dev/) SPA:

![image](https://user-images.githubusercontent.com/111092/161531530-11ebdd28-0738-4612-a323-e2db5038a501.png)

What I think is needed with the current architecture is the ability to add multiple fallbacks, where each fallback propagates down the line if it doesn't match the given route.

**Comment by davidpdrsn** [comment]
Serving assets directly at the root feels quite odd to me. I haven't worked on an app that did that 🤔 But its something we can add support for.

Maybe something like:

```rust
ServeDir::new("...").fallback(ServeFile::new("index.html"))
```

That would call `ServeFile` if `ServeFile` returns 404. You could then use that as your fallback service with axum so it would be called for any unknown routes.

**Comment by jplatte** [comment]
> Maybe something like:
> 
> ```rust
> ServeDir::new("...").fallback(ServeFile::new("index.html"))
> ```

Which is what I've been advocating for the entire time 😛

**Comment by davidpdrsn** [comment]
hehe yeah I know 😜 takes time to change ones mind. I still would like to not have to build special systems for this but have more general combinators. Not sure how though.

**Comment by udoprog** [comment]
@davidpdrsn That would work, all though it might come across as a bit architecturally peculiar that `ServeDir` has its own fallback routing. I'll defer that decision to you though!

**Comment by davidpdrsn** [comment]
Well if you just wanna say within axum then its easy 😜

```rust
let app = Router::new().fallback(fallback.into_service());

async fn fallback(method: Method, uri: Uri, headers: HeaderMap) -> Response {
    let make_request = move || {
        let mut request = Request::new(Body::empty());
        *request.method_mut() = method.clone();
        *request.uri_mut() = uri.clone();
        *request.headers_mut() = headers.clone();
        request
    };

    let response = match ServeDir::new("assets").oneshot(make_request()).await {
        Ok(res) => res,
        Err(err) => return (StatusCode::INTERNAL_SERVER_ERROR, err.to_string()).into_response(),
    };

    if response.status() == StatusCode::NOT_FOUND {
        match ServeFile::new("index.html").oneshot(make_request()).await {
            Ok(res) => res.into_response(),
            Err(err) => (StatusCode::INTERNAL_SERVER_ERROR, err.to_string()).into_response(),
        }
    } else {
        response.into_response()
    }
}
```

axum's router does have a "fallback" today however it only works for proper routes that you've defined with `.router("/something", _)`.

`ServeDir` is totally separate and just accepts all requests. It doesn't participate in axum's routing in that way. And there is no general way for services defined outside of axum to say whether they can or could handle a request. Returning 404 doesn't necessarily mean the service couldn't accept the request.

**Comment by udoprog** [comment]
If handling chained fallbacks is a route (no pun intended) you'd like to investigate it might be a good idea to open an issue on the Axum project. For now, I fully support the custom fallback handler for `ServeDir` as a stopgap solution!

Below follow a bit of technical musings:

> `ServeDir` is totally separate and just accepts all requests. It doesn't participate in axum's routing in that way. And there is no general way for services defined outside of axum to say whether they can or could handle a request. Returning 404 doesn't necessarily mean the service couldn't accept the request.

Yeah, chaining fallbacks by relying on HTTP codes as a signalling mechanism would not be the way I'd prefer to do it either (since like you said, it might be a legitimate response). The alternative mechanisms available could be:

Define an error variant for `fallback` which indicates that "I did not match the request" ([instead of `Infallible`](https://docs.rs/axum/latest/axum/routing/struct.Router.html#method.fallback)) and process that internally. This error can also be used to ship the original request back to the caller to avoid cloning all though some care need to be taken not to consume the request body (e.g. in case it's streamed), which is why the next option might be preferable:

Govern fallbacks entirely using a new very Service-like trait that `ServeDir` / `ServeFile` can be coerced into. E.g. `FallbackHandler`. The hope would be to build an API which can help avoid the pitfall of consuming the request body until it's determined that the fallback handler can process the request.

**Comment by davidpdrsn** [comment]
We're adding fallback support to `ServeDir`. If people want something more custom I'd say roll your own 😊 If you're using axum there is also [`SpaRouter`](https://docs.rs/axum-extra/latest/axum_extra/routing/struct.SpaRouter.html).
