### ISSUE TITLE
Expose compression level  on CompressionLayer

### ISSUE THREAD

**Issue by Zerowalker** [tower-rs/tower-http#245]
### Motivation

Being able to set the compression level will allow one to tweak the settings for optimal speed/compression.
It can be quite a big difference in speed mostly, especially if things are at max.

### Proposal

My thoughts are that `with_quality` is exposed from `async_compression`.
[https://docs.rs/async-compression/latest/src/async_compression/macros.rs.html#19](url)

The interesting one is the  `Level::Precise` so just having access to that should give much of the customization
[https://docs.rs/async-compression/latest/src/async_compression/lib.rs.html#208](url)

### Alternatives

Haven't tried it but i guess one could manually implement their own compression layer,
or do the compression in the request handler.
I believe it would be quite unnecessary to do that workaround when there's already a `CompressionLayer` available.

:)

**Comment by Zerowalker** [comment]
I will try look into it, not sure i can provide code that are up to par though haha.
But i take that as it's not a bad idea, so that's a start:)

**Comment by Nehliin** [comment]
Happy to help with feedback!

**Comment by barvirm** [comment]
@Nehliin Do you have any design ideas? How propagate compression level to the encoders?
Current `DecorateAsyncRead` is not expandable for these changes.

**Comment by Nehliin** [comment]
Haven't looked into the details yet. Can look at it next week sometime

**Comment by barvirm** [comment]
@Nehliin Thank you

**Comment by davidpdrsn** [comment]
I think a builder method on `CompressionLayer` and `Compression` a la

```rust
CompressionLayer::new().level(the_level)
```

is fine.

I think we can copy https://docs.rs/async-compression/latest/async_compression/enum.Level.html into tower-http and internally map between them, to not expose things from async-compression.
