### ISSUE TITLE
Moving to 0.3.0: no `ServiceBuilderExt` in the root?

### ISSUE THREAD

**Issue by zeeshanlakhani** [tower-rs/tower-http#253]
## Bug Report

Error when building code w/ the new version (0.3.0):

```shell
error[E0432]: unresolved import `tower_http::ServiceBuilderExt`
  --> src/middleware.rs:22:5
   |
22 |     ServiceBuilderExt,
   |     ^^^^^^^^^^^^^^^^^ no `ServiceBuilderExt` in the root
```

It was fine previously, and it seems like the path shouldn't change? https://docs.rs/tower-http/latest/tower_http/trait.ServiceBuilderExt.html. 

### Version

0.3.0

### Platform

- Darwin Kernel Version 20.6.0 (OSX)
- As well as on a Github-Actions machine running Linux.

### Description

The import part of the code (as it was on 0.2.5):

```rust
use tower::ServiceBuilder;
use tower_http::{
    classify::ServerErrorsFailureClass,
    request_id::{MakeRequestId, RequestId},
    trace::TraceLayer,
    ServiceBuilderExt,
};
```

**Comment by jplatte** [comment]
What crate features did you activate for `tower-http`?

**Comment by zeeshanlakhani** [comment]
@jplatte  `["catch-panic", "request-id", "sensitive-headers", "trace"]`.

**Comment by zeeshanlakhani** [comment]
Maybe I can remove request-id?

**Comment by jplatte** [comment]
I don't know whether you can remove `request-id`, but you need to enable the `util` feature for `ServiceBuilderExt` to be available. It looks like the docs are buggy and don't show this.

**Comment by davidpdrsn** [comment]
You need to enable the "util" feature and you also needed that in 0.2 so not sure what's going on.

**Comment by zeeshanlakhani** [comment]
@davidpdrsn oh odd. I'll test and update. Thanks for the help.

**Comment by jplatte** [comment]
> not sure what's going on.

@davidpdrsn I still think that this is a case of

> relying on another crate activating the features you use, and now that no longer works because that indirect dependency is still using tower-http 0.2

**Comment by davidpdrsn** [comment]
Yeah that's probably it. God I don't like cargo features. So many footguns both for users and lib developers 😅

**Comment by zeeshanlakhani** [comment]
@davidpdrsn It was (adding `util`). Thanks for that.
