### ISSUE TITLE
CORS: Multiple origins for access-control-allow-origin when using `AllowOrigin::list`

### ISSUE THREAD

**Issue by zhihengq** [tower-rs/tower-http#255]
### Version

0.3.0

### Description

I tried this code:

```rs
CorsLayer::new().allow_methods(Any).allow_origin(AllowOrigin::list([
    "http://localhost:3000",
    "http://192.168.1.10:3000",
]));
```

Send requests from origin `http://localhost:3000`.

I expected to see this happen:
```http
access-control-allow-origin: http://localhost:3000
```

Instead, this happened:
```http
access-control-allow-origin: http://localhost:3000,http://192.168.1.10:3000
```

According to [Access-Control-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin), there should not be multiple origins.

**Comment by jplatte** [comment]
Oh, I thought that this wasn't such a dynamic thing. So it's impossible to do a request without an origin and learn about all the allowed ones, that's kind of weird / unfortunate.

I'll write a fix later today.
