### ISSUE TITLE
Switch examples to clap 3.x from structop

### ISSUE THREAD

**Issue by wolthom** [tower-rs/tower-http#260]
The examples still use `structop`, which has been integrated into clap (with the `derive` feature since 3.x).
Would a PR for moving them to clap be relevant?

**Comment by davidpdrsn** [comment]
Yes!

**Comment by wanderinglethe** [comment]
Looks like this has been done in !261

**Comment by wolthom** [comment]
Ah, I completely forgot to close the related issue. Sorry!
I'll close it now
