### ISSUE TITLE
Get request data for `TraceLayer::on_response` handler

### ISSUE THREAD

**Issue by Gricha** [tower-rs/tower-http#269]
### Motivation

Currently, when defining TraceLayer, we can define separately handlers for request coming in and response coming out. Each of them can log the respective parts - on request we can log what Method/Uri came in; on response, we can log whether result was successful (ie error code) etc.

The problem I have with the current approach is that I cannot build a single line of log that would represent data for a given request. Ideally I'd like to have a log that looks something like this:
```
400 GET /user/abc123/ duration=20ms
```
This makes grokking through logs significantly simpler.

### Proposal

Include reference to Request (or other form of passing requests metadata?) to `on_response` handler.

### Alternatives

I thought of two alternatives:
* Write my own simple tracing layer that does what I want, with probably less features than TraceLayer provides
* Inject data that's relevant to me in `AddExtension` layer. Unsure how to do that exactly, but if I could take data off request and just inject it into Response, that would then allow me to extract proper metadata in the handler. This seems like a bit complicated path that I am not exactly sure how to perform.

**Comment by Gricha** [comment]
To visualize context a bit better, this is roughly would I'd love to achieve:
```
use std::time::Instant;

use axum::{http::Request, middleware::Next, response::IntoResponse};

pub async fn trace_request<B>(req: Request<B>, next: Next<B>) -> impl IntoResponse {
    let start = Instant::now();
    let uri = req.uri().clone();
    let method = req.method().clone();

    let resp = next.run(req).await;

    let status_code = resp.status();
    let duration = Instant::now() - start;

    if (400..=599).contains(&status_code.as_u16()) {
        tracing::error!(
            "{} {} {} duration={}ms",
            status_code,
            method,
            uri,
            duration.as_millis()
        );
    } else {
        tracing::info!(
            "{} {} {} duration={}ms",
            status_code,
            method,
            uri,
            duration.as_millis()
        );
    }

    tracing::info!(
        "{} {} {} duration={}",
        method,
        uri,
        status_code,
        duration.as_millis()
    );

    resp
}

```

And the logs it'll give me look like this:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/875316/167748694-2944c40e-00e0-4746-82e1-375c2e353425.png">

**Comment by davidpdrsn** [comment]
The intention is that such information is carried in the span, created by the [`MakeSpan`](https://docs.rs/tower-http/latest/tower_http/trace/trait.MakeSpan.html).

That means `TraceLayer::new_for_http().on_request(())` will get you most of the way there:

```
2022-05-11T07:09:45.292337Z DEBUG request{method=GET uri=/ version=HTTP/1.1}: tower_http::trace::on_response: finished processing request latency=0 ms status=200
```

You'll still get two lines if something fails:

```
2022-05-11T07:07:45.850757Z DEBUG request{method=GET uri=/error version=HTTP/1.1}: tower_http::trace::on_response: finished processing request latency=0 ms status=500
2022-05-11T07:07:45.850904Z ERROR request{method=GET uri=/error version=HTTP/1.1}: tower_http::trace::on_failure: response failed classification=Status code: 500 Internal Server Error latency=0 ms
```

You can of course silence the failure with `.on_failure(())` and manually change the level in `.on_response` if the status code is an error. Since you're using axum you don't need to [consider errors](https://docs.rs/axum/latest/axum/error_handling/index.html#axums-error-handling-model).

If that isn't what you want the I'd say writing your own middleware is totally fine.

**Comment by Gricha** [comment]
Ah that is fantastic, I didn't realize I can put that information in span, that makes sense! Thanks a lot David!

**Comment by Kinrany** [comment]
Is the span not supposed to only carry information that identifies the span? Adding anything else means bloating every single event within the span with information that can be recovered by collecting all the events of the span anyway.
