### ISSUE TITLE
Why doesn't it have cors?????

### ISSUE THREAD

**Issue by KishiTheMechanic** [tower-rs/tower-http#281]
```
error[E0432]: unresolved import `tower_http::cors`
  --> src/main.rs:15:17
   |
15 | use tower_http::cors::{CorsLayer, Origin};
   |                 ^^^^ could not find `cors` in `tower_http`
```

**Comment by davidpdrsn** [comment]
I suppose you found this out but you gotta enable the `cors` feature

![image](https://user-images.githubusercontent.com/718941/177323977-129f05e2-0bdb-471e-918a-c2370c0c8964.png)

**Comment by KishiTheMechanic** [comment]
Thank you! Yes, now it's working well. Great package.
