### ISSUE TITLE
ValidateRequest: Accept header parsing is incorrect

### ISSUE THREAD

**Issue by davidpdrsn** [tower-rs/tower-http#291]
Turns out parsing the `Accept` header isn't just a matter of splitting on commas, like we do [here](https://github.com/tower-rs/tower-http/blob/master/tower-http/src/validate_request.rs#L387).

See https://github.com/http-rs/http-types/issues/349 for more details.

**Comment by davidpdrsn** [comment]
@82marbag do you wanna look into this?

**Comment by glasser** [comment]
I asked nicely and now this library has a parser for this you can use: https://github.com/picoHz/mediatype/issues/4 https://docs.rs/mediatype/latest/mediatype/struct.MediaTypeList.html

**Comment by 82marbag** [comment]
@davidpdrsn should I add that as a dependency? Are you ok with it?

**Comment by davidpdrsn** [comment]
That crate seems similar to [mime](https://crates.io/crates/mime) which I believe tower-http already uses already.

**Comment by davidpdrsn** [comment]
If we can use mime then I think we should do that.

**Comment by 82marbag** [comment]
I would not re-implement that in tower-http, I'd either
* ask to implement or implement it myself in mime
* use the mediatype crate
Do you have any other suggestion or which of these should I go for?

**Comment by jplatte** [comment]
I think the previous reply was already an endorsement of your first option, and I agree.
