### ISSUE TITLE
SetSensitiveRequestHeaders layer does not mark all sensitive values

### ISSUE THREAD

**Issue by quininer** [tower-rs/tower-http#293]
## Bug Report

https://github.com/tower-rs/tower-http/blob/371bb3fcad2a5be548e00651c98da5b85a5fd443/tower-http/src/sensitive_headers.rs#L236

Currently `SetSensitiveRequestHeaders` and `SetSensitiveResponseHeaders` will only mark the first value, which can cause sensitive headers with multiple values to not be properly marked, such as `set-cookie`.

### Version

master

### Platform

Any

### Description

We can get all values of a header with [`get_all`](https://docs.rs/http/latest/http/header/struct.HeaderMap.html#method.get_all), but it doesn't provide a mut version, so we can't mark sensitive.

The best way is for http crate to add a `get_all_mut` method, and secondly we can rebuild the whole `HeaderMap`.

**Comment by seanmonstar** [comment]
It should be doable using `HeaderMap::entry()`, as an occupied entry has a method `iter_mut`.
