### ISSUE TITLE
CorsLayer `very_permissive` does not appear to allow credentials

### ISSUE THREAD

**Issue by mmalenic** [tower-rs/tower-http#297]
### Version

0.3.4

### Platform

Linux

### Crates

tower-http

### Description

The CorsLayer `very_permissive` function does not appear to allow credentials, even though this is what is stated in the documentation.
https://github.com/tower-rs/tower-http/blob/aeb6e91a609723bd2ac0d8e67fe94574e5f1eb35/tower-http/src/cors/mod.rs#L135-L149

For example, the following:

```rust
fn main() {
    println!("{:#?}", CorsLayer::very_permissive());
}
```

prints:
```
CorsLayer {
    allow_credentials: No,
    allow_headers: MirrorRequest,
    allow_methods: MirrorRequest,
    allow_origin: Predicate,
    expose_headers: Const(
        None,
    ),
    max_age: Exact(
        None,
    ),
    vary: Vary(
        [
            "origin",
            "access-control-request-method",
            "access-control-request-headers",
        ],
    ),
}

```

Whereas I would expected `allow_credentials` to be set to `Yes`.

Is this the intended behaviour?

**Comment by jplatte** [comment]
Sorry, this seems to have been an oversight when adding that constructor. I've posted a PR with a fix.

**Comment by mmalenic** [comment]
No worries, thanks @jplatte!
