### ISSUE TITLE
Filtering Requests

### ISSUE THREAD

**Issue by erichulburd** [tower-rs/tower-http#307]
### Motivation

Clients or servers may commonly want to exclude particular paths from tracing, for instance a health check that a load balancer frequently calls. It would be great to have an easy way to omit particular gRPCs and HTTP method/ maths from tracing at the user's discretion.

The Python gRPC OTel instrumentation library supports this using the concept of [filters](https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/grpc/grpc.html#filters).

### Proposal

It seems like the best thing to do would be to create a `FilterableMakeSpan`. Here is a _very_ rough idea of what I'd propose. 

```rs
#[derive(Debug, Clone)]
pub struct FilterableMakeSpan<B, F> where
    F: Fn(&Request<B>) -> bool,
{
    filter: F, // unsure if I'm event using generics correctly here, but the idea should be clear.
    pub parent: MakeSpan<B>,
}

impl DefaultMakeSpan {
    pub fn new() -> Self {
        Self {
            filter: |_| { true },
            parent: DefaultMakeSpan::new(),
        }
    }

    pub fn only_paths(mut self, paths: HashSet<String>) -> Self {
        self.filter =|req: &Request<B>| -> bool {
          paths.contains(req.uri())
        };
        self
    }

    pub fn not_paths(mut self, paths: HashSet<String>) -> Self {
        self.filter =|req: &Request<B>| -> bool {
          !paths.contains(req.uri())
        };
        self
    }
}

impl Default for FilterableMakeSpan {
    fn default() -> Self {
        Self::new()
    }
}

impl<B> MakeSpan<B> for FilterableMakeSpan {
    fn make_span(&mut self, request: &Request<B>) -> Span {
         if self.filter(request) {
             self.parent.make_span(request)
         } else {
             trace::Span::none()
         }
    }
}
```

I realize I might get push back that this is not an API you want to support. I would still include something along the lines of the above in the documentation.

### Alternatives

None that are immediately apparent to me.

**Comment by davidpdrsn** [comment]
I think this makes sense to support one way or the another. I was first thinking that it could be solved at the routing level. For example you can do this with axum

```rust
let needs_tracing = Router::new()
    .route(...)
    .layer(TraceLayer::new_for_http());

let doesnt_need_tracing = Router::new()
    .route(...);

let app = needs_tracing.merge(doesnt_need_tracing);
```

but that obviously wont work for clients.

However I'm thinking that maybe some general "don't run this middleware on this request" type thing would be nice to have in tower. That feels like it would work for this without being specific to this use case. Could look something like this

```rust
ServiceBuilder::new()
    .layer(If::new(
        |request| {
            request.uri().starts_with("/api")
        },
        TraceLayer::new_for_http(),
    ))
    .service(client)
```

No idea if thats actually possible. Its just the first thing that came to my head.

What do you think?

**Comment by erichulburd** [comment]
At a glance, that would accomplish everything I'm presently looking to accomplish and support a broader set of use cases, so I would endorse that functionality.

Essentially, this just boils down to implementing `Service<Request<ReqBody>> for If`, which would be something roughly along the lines of the following, right?

```rs
pub struct If<S, F, B>  where
    F: Fn(&Request<B>) -> bool,
    B: Body,
{
    pub(crate) inner: S,
    pub(crate) condition: F,
    pub(crate) consequent: Layer
}

impl<
        S,
        ReqBody,
        ResBody,
    > Service<Request<ReqBody>>
    for If<S>
where
    S: Service<Request<ReqBody>, Response = Response<ResBody>>,
    ReqBody: Body,
    ResBody: Body,
    ResBody::Error: fmt::Display + 'static,
    S::Error: fmt::Display + 'static,
{

    fn poll_ready(&mut self, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        self.consequent.poll_ready(cx)
    }

    fn call(&mut self, req: Request<ReqBody>) -> Self::Future {
        if self.condition(req) {
          self.consequent.call(req)
        } else {
          self.inner.call(req)
        }
    }
}
```

**Comment by davidpdrsn** [comment]
Yeah that seems to be going in the right direction. I think I'll close this now but I encourage you to open an issue about this in the [tower repo](https://github.com/tower-rs/tower).

**Comment by erichulburd** [comment]
As I was investigating this, it became clear that [tracing_subscriber::EnvFilter](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html) enables per-layer filtering. That seems pretty well standardized, so I won't implement `tower::If`.

**Comment by nbari** [comment]
Hi @erichulburd did you manage to filter (not create any span) for example for path `/health` using EnvFilter? if yes, could you please share an example of doing this? I have this issue https://github.com/tokio-rs/tracing-opentelemetry/issues/97
