### ISSUE TITLE
`ServeDir` doesn't use fallback on non-utf8 request path

### ISSUE THREAD

**Issue by wfraser** [tower-rs/tower-http#308]
### Version

0.3.4

### Platform

Linux

### Crates

tower-http

### Description

If a client makes a request which does not percent-decode to valid UTF-8 (like `http://my-host/weird_%c3%28_path`), the `serve_dir` service [unconditionally responds with 404](https://github.com/tower-rs/tower-http/blob/69b6f47976c6dfb6df32b8781f618e86248fd7c9/tower-http/src/services/fs/serve_dir/future.rs#L141-L143), even if a fallback handler is set up.

This is interfering with my use case where I want to handle any request where the file doesn't exist and forward it to another handler which will proxy it elsewhere. Except for this edge case, using `ServeDir::new(root).call_fallback_on_method_not_allowed(true).fallback(other_handler)` has worked great. It feels like an inconsistency to me to not allow any fallback for this case.

<details>
  <summary>Example server code and test cases</summary>

```rust
// [dependencies]
// axum = "0.6.1"
// http = "0.2.8"
// tokio = { version = "1.22.0", features = ["full"] }
// tower = "0.4.13"
// tower-http = { version = "0.3.4", features = ["fs"] }

use std::convert::Infallible;
use std::io;
use axum::extract::OriginalUri;
use axum::response::IntoResponse;
use axum::routing::{get, get_service, Router};
use http::StatusCode;
use tower::util::ServiceExt;
use tower_http::services::ServeDir;

#[tokio::main]
async fn main() {
    let dir = ServeDir::new(".")
        .append_index_html_on_directories(false)
        .call_fallback_on_method_not_allowed(true)
        .fallback(get(fallback_handler).map_err(|e: Infallible| -> io::Error { match e {} }));

    let app = Router::new()
        .route("/*anything", get_service(dir).handle_error(handle_io_error));

    axum::Server::bind(&"127.0.0.1:9999".parse().unwrap())
        .serve(app.into_make_service())
        .await
        .expect("server error");
}

async fn fallback_handler(OriginalUri(uri): OriginalUri) -> impl IntoResponse {
    eprintln!("fallback handler invoked for {uri}");
    "hello from fallback handler"
}

async fn handle_io_error(e: io::Error) -> impl IntoResponse {
    (StatusCode::INTERNAL_SERVER_ERROR, format!("I/O error: {e}"))
}
```

* `curl -v http://127.0.0.1:9999/Cargo.toml`: returns the file as expected
* `curl -v http://127.0.0.1:9999/notfound`: returns 200 with `hello from fallback handler` as expected
* `curl -v http://127.0.0.1:9999/oops%c3%28`: returns 404 with no output and fallback is not invoked at all

</details>

**Comment by Nehliin** [comment]
I can probably look into this next week. Have some other ideas for serving files that I want to do as well.
