### ISSUE TITLE
Support for Access-Control-Allow-Private-Network

### ISSUE THREAD

**Issue by timothy-s-dev** [tower-rs/tower-http#314]
### Motivation

Chrome is removing/has removed the ability to send requests to private network endpoints from public websites:
https://developer.chrome.com/blog/private-network-access-preflight/

There is a pre-flight header it sends now (`Access-Control-Request-Private-Network`) and expects in the response to allow those requests through.

### Proposal

Perhaps a new method alongside `allow_headers`/`allow_methods`/etc on `CorsLayer` (`allow_private_network_access`?) that provides the correct response header for the preflight request?

**Comment by jplatte** [comment]
Help is still wanted, #315 is complete as far as the main logic is concerned, but is missing a unit test and I don't want to dedicate more time to it (I don't actually have a use case for this myself).

**Comment by jplatte** [comment]
Done in #373.
