### ISSUE TITLE
CompressionLayer add zstd support

### ISSUE THREAD

**Issue by beckend** [tower-rs/tower-http#319]
### Motivation
It's new, but it's starting to pick up.
Here is a curl request:
```shell
curl --compressed http://whatever.com/my/endpoint
> GET /my/endpoint HTTP/1.1
> Host: whatever.com
> User-Agent: curl/7.87.0
> Accept: */*
> Accept-Encoding: deflate, gzip, br, zstd

```

It's also available in envoy proxy serving such requests.
https://github.com/envoyproxy/envoy/tree/main/examples/zstd

**Comment by davidpdrsn** [comment]
That should be quite straightforward seeing as [async-compression already supports it](https://docs.rs/async-compression/latest/async_compression/#compression-algorithm).
