### ISSUE TITLE
cargo test failed!

### ISSUE THREAD

**Issue by mineralres** [tower-rs/tower-http#327]
### Version
latest main branch

### Platform
ubuntu 22.04

### Crates
services::fs::serve_dir

### Description
when i run `cargo test` , get the following errors:

failures:

---- src/lib.rs - (line 95) stdout ----
error[E0432]: unresolved imports `tower_http::decompression`, `tower_http::set_header`, `tower_http::trace`
 --> src/lib.rs:97:5
  |
4 |     decompression::DecompressionLayer,
  |     ^^^^^^^^^^^^^ could not find `decompression` in `tower_http`
5 |     set_header::SetRequestHeaderLayer,
  |     ^^^^^^^^^^ could not find `set_header` in `tower_http`
6 |     trace::TraceLayer,
  |     ^^^^^ could not find `trace` in `tower_http`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
Couldn't compile the test.
---- src/classify/status_in_range_is_error.rs - classify::status_in_range_is_error::StatusInRangeAsFailures (line 12) stdout ----
error[E0432]: unresolved import `tower_http::trace`
 --> src/classify/status_in_range_is_error.rs:13:18
  |
4 | use tower_http::{trace::TraceLayer, classify::StatusInRangeAsFailures};
  |                  ^^^^^ could not find `trace` in `tower_http`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
Couldn't compile the test.
---- src/lib.rs - (line 17) stdout ----
error[E0432]: unresolved imports `tower_http::add_extension`, `tower_http::compression`, `tower_http::propagate_header`, `tower_http::sensitive_headers`, `tower_http::set_header`, `tower_http::trace`, `tower_http::validate_request`
  --> src/lib.rs:19:5
   |
4  |     add_extension::AddExtensionLayer,
   |     ^^^^^^^^^^^^^ could not find `add_extension` in `tower_http`
5  |     compression::CompressionLayer,
   |     ^^^^^^^^^^^ could not find `compression` in `tower_http`
6  |     propagate_header::PropagateHeaderLayer,
   |     ^^^^^^^^^^^^^^^^ could not find `propagate_header` in `tower_http`
7  |     sensitive_headers::SetSensitiveRequestHeadersLayer,
   |     ^^^^^^^^^^^^^^^^^ could not find `sensitive_headers` in `tower_http`
8  |     set_header::SetResponseHeaderLayer,
   |     ^^^^^^^^^^ could not find `set_header` in `tower_http`
9  |     trace::TraceLayer,
   |     ^^^^^ could not find `trace` in `tower_http`
10 |     validate_request::ValidateRequestHeaderLayer,
   |     ^^^^^^^^^^^^^^^^ could not find `validate_request` in `tower_http`

error: aborting due to previous error

**Comment by davidpdrsn** [comment]
You need to use `cargo test --all-features`.

**Comment by jplatte** [comment]
Well, it would be nice if feature cfg's were applied to test code as well so testing with default or custom feature set works..

**Comment by davidpdrsn** [comment]
Yeah that'd be nice.
