### ISSUE TITLE
failed to resolve: could not find `Client` in `hyper` [E0433] could not find `Client` in `hyper`

### ISSUE THREAD

**Issue by acche** [tower-rs/tower-http#340]
let mut client = ServiceBuilder::new()
        .layer(SetRequestHeaderLayer::overriding(
            header::AUTHORIZATION,
            HeaderValue::from_str(&format!("Bearer {}", token)).unwrap(),
        ))
        .service(hyper::Client::new());

failed to resolve: could not find `Client` in `hyper` [E0433] could not find `Client` in `hyper`

Quite confuse about the version on rust.

How to fix this problem?

**Comment by acche** [comment]
add this 
`hyper = { version = "0.14.25", features = ["Client"] }`
to cargo.toml ?

**Comment by Nehliin** [comment]
yes but with lower case 'C'.
