### ISSUE TITLE
Strangely high latency from ServeDir

### ISSUE THREAD

**Issue by MorganR** [tower-rs/tower-http#352]
## Bug Report

`ServeDir` seems to have up to 100x the latency of a simple `Vec<u8>` response read via `tokio::fs::read`.

### Version

0.4.0

### Platform

Ubuntu 22.04.2 via WSL:

Linux MORGAN-SURFACE 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Description

I recently tried using tower's `ServeDir` middleware to serve some files with [axum](https://docs.rs/axum/latest/axum/), and noticed unusually high latency compared with some other static file servers I was testing.

So, I tried a really simple comparison between ServeDir's performance and a standard `tokio::fs:read` ([repo](https://github.com/MorganR/tower-serve-dir-perf)). You can see in the [results](https://github.com/MorganR/tower-serve-dir-perf/blob/main/results.txt) that **ServeDir has almost 100x the latency of a simple tokio read.** I would expect so see similarly strong performance from ServeDir, and this seems like an unreasonably high latency increase.

I'll keep digging in here to try to see if I can figure out where the latency is coming from, but wanted to flag this here in case anyone has any ideas.

**Comment by MorganR** [comment]
From a little more digging, it looks like the latency arises from the file streaming being done by `AsyncReadBody`. I replicated just this behavior in the [test repo](https://github.com/MorganR/tower-serve-dir-perf), and found similar latency to `ServeDir`.

**Comment by davidpdrsn** [comment]
That sounds familiar. I think we had a similar issue in the past with https://github.com/tower-rs/tower-http/issues/136

**Comment by MorganR** [comment]
I may have narrowed it down a _little_ further. Compare the `read_async` function with `stream_to_body` function in [main.rs](https://github.com/MorganR/tower-serve-dir-perf/blob/main/src/main.rs). 

`read_async` uses a `ReaderStream`, but returns the file in a single response. This performs great, at about 2x the speed of `tokio::fs:read`. The slow down is likely because I'm not super familiar with streams and this implementation duplicates a buffer.

However, `stream_to_body` is still orders of magnitude slower. The core difference is that it uses the `http-body::Body` trait to stream the response. So, the latency doesn't seem to be caused by a broader issue with `ReaderStream` or streams generally, but it could be specific to `http-body`'s mechanisms.

I have no familiarity with `http-body`, so I might progress fairly slowly from here. But please do jump in if you have ideas.

**Comment by MorganR** [comment]
The issue seems to specifically occur if a call to `Body::poll_data` ever returns `Poll::Pending`. @davidpdrsn , do you know which part of the Axum/Tokio/Hyper stack is responsible for polling Body? This issue should likely be assigned there instead of to tower.

Details:

In a separate branch ([main.rs](https://github.com/MorganR/tower-serve-dir-perf/blob/body/src/main.rs)), I've removed all file I/O, and implemented two very simple `Body` structs:

* `SimpleBody`: returns a number of lines of text, providing one line per call to `Body::poll_data`. This performs almost identically to the simple `single` case that returns all lines as a single string.
* `DelayedBody`: does the same thing as `SimpleBody`, except it returns `Poll::Pending` on every other call to `Body::poll_data`. As soon as `Poll::Pending` is returned, the latency jumps from a couple hundred microseconds to about 50 milliseconds.

**Comment by jplatte** [comment]
If you just return `Poll::Pending` from a future / stream without registering the waker for the current task to be awoken again when progress can potentially be made again, it is to be expected that it will take longer than necessary for the next poll to happen.

Can you try to call `context.waker().wake_by_ref()` before returning `Poll::Pending` inside your `DelayBody`? If that fixes the problem, then the real bug is likely about the body type used by `ServeDir` not setting itself up for wakeup correctly.

**Comment by MorganR** [comment]
I was also worried that this could be an issue unique to WSL, but I observed similar behavior running in a Debian VM on GCP, so I don't think that's the case.

**Comment by davidpdrsn** [comment]
I ran a quick micro benchmark.

Code:

```rust
use http::{Request, StatusCode};
use tokio::io::AsyncReadExt;
use tower::Service;

#[tokio::main]
async fn main() {
    let path = "..."; // some large file

    match &*std::env::args().nth(1).unwrap() {
        "fs" => {
            let mut file = tokio::fs::File::open(path).await.unwrap();
            let mut buf = Vec::new();
            file.read_to_end(&mut buf).await.unwrap();
        }
        "serve" => {
            // `ServeFile` is a small wrapper around `ServeDir`
            let mut svc = tower_http::services::ServeFile::new(path);
            let res = svc.call(Request::new(())).await.unwrap();
            assert_eq!(res.status(), StatusCode::OK);
            hyper::body::to_bytes(res).await.unwrap();
        }
        _ => {
            panic!("wat")
        }
    }
}
```

Hyperfine results:

```
❯ hyperfine --warmup 3 "./target/release/test-binary fs" "./target/release/test-binary serve"

Benchmark 1: ./target/release/test-binary fs
  Time (mean ± σ):      53.0 ms ±   1.7 ms    [User: 11.8 ms, System: 39.7 ms]
  Range (min … max):    49.8 ms …  57.2 ms    56 runs

Benchmark 2: ./target/release/test-binary serve
  Time (mean ± σ):      82.3 ms ±   2.6 ms    [User: 24.6 ms, System: 56.1 ms]
  Range (min … max):    78.4 ms …  89.6 ms    36 runs

Summary
  './target/release/test-binary fs' ran
    1.55 ± 0.07 times faster than './target/release/test-binary serve'
```

So while it seems tower-http is a bit slower, it's not much slower. And certainly not 100x. So yes maybe the issue is elsewhere?

**Comment by jplatte** [comment]
Try with a small file? This issue is about latency, not throughput.

**Comment by davidpdrsn** [comment]
I ran it with `src/main.rs` from my benchmark script. Seems to be the same story

```
Benchmark 1: ./target/release/test-binary fs
  Time (mean ± σ):       1.7 ms ±   0.1 ms    [User: 0.7 ms, System: 1.3 ms]
  Range (min … max):     1.4 ms …   2.8 ms    1324 runs

Benchmark 2: ./target/release/test-binary serve
  Time (mean ± σ):       1.7 ms ±   0.1 ms    [User: 0.7 ms, System: 1.3 ms]
  Range (min … max):     1.4 ms …   2.4 ms    1680 runs

Summary
  './target/release/test-binary serve' ran
    1.01 ± 0.12 times faster than './target/release/test-binary fs'
```

**Comment by MorganR** [comment]
Hey folks, looks like this occurs as a result of the Nagle algorithm in TCP (see [issue in hyper](https://github.com/hyperium/hyper/issues/3187)). 

The issue can be resolved by enabling `tcp_nodelay` to disable Nagle.
