### ISSUE TITLE
Support concatenated GZIP streams

### ISSUE THREAD

**Issue by cmackenzie1** [tower-rs/tower-http#353]
### Motivation

GZIP files have a property where multiple GZIP files concatenated together are still considered a valid GZIP file. Currently, the GZIP decompression does not use the async-compression [`multiple_members`](https://docs.rs/async-compression/latest/async_compression/tokio/bufread/struct.GzipDecoder.html#method.multiple_members), which allows for streams of multiple gzip files, one after another. 

### Proposal

Allow configuring the `multiple_members` attribute for the decoders so users can enable it. 

### Alternatives

- Expose a new Multi*Decoders that allow for reading streams of files.

**Comment by davidpdrsn** [comment]
Any reason we wouldn't enable that all the time?

**Comment by cmackenzie1** [comment]
> Any reason we wouldn't enable that all the time?

Nothing that I can think of. These are technically valid gzips and most libraries handle this automatically. At least that's the case for Go and the bash command.

**Comment by cmackenzie1** [comment]
@davidpdrsn created #354.
