### ISSUE TITLE
Minimize futures crates dependency

### ISSUE THREAD

**Issue by tottoto** [tower-rs/tower-http#436]
### Motivation

Allows users to depend on the minimum dependencies which are actually used.

### Proposal

Changes `tower-http` to depends on `futures-core` and `futures-util` when they are actually needed, especially about the latter. This includes porting `BoxFuture` to `tower-http`'s code. This proposal's drawback is increasing the maintenance cost to control the crates condition, and the profit can be affected by the other dependencies.

### Alternatives

Keeps depending on `futures-util`.

**Comment by jplatte** [comment]
Can we close this as done in #434? All remaining uses of the `futures` crate are in examples, which only matters for users that copy-paste those examples, and we have #435 for it.

**Comment by tottoto** [comment]
What I tried to discuss the future crates is that futures-* crates family. For examples, regarding trace feature, `tower-http` seems not to need to use `futures-util` and can use `futures-core` directly instead.

**Comment by jplatte** [comment]
Oh, okay! In that case, disregard my comment. I'd be happy to merge a PR that implements that change and similar ones.
