### ISSUE TITLE
Add OpendalLayer to allow serving files from differnet storage services

### ISSUE THREAD

**Issue by Xuanwo** [tower-rs/tower-http#449]
- [x] I have looked for existing issues (including closed) about this

**I'm interested in implementing this for `tower-http`.**

### Motivation

[`ServeDir`](https://github.com/tower-rs/tower-http/tree/main/tower-http/src/services/fs/serve_dir) functions properly, but is limited to the local file system. This limitation makes it challenging to serve content from sources like `memory`, `redis`, `s3`, or `moka`.

What if we expand its capabilities to include all types of storage services?

### Proposal

[OpenDAL](https://github.com/apache/incubator-opendal) is a data access layer that allows users to easily and efficiently retrieve data from various storage services in a unified way.

![image](https://github.com/tower-rs/tower-http/assets/5351546/d9154d16-ee94-4fb9-9008-35c369646b66)

We can implement a new service that based on `opendal` and provide similiar features to `ServeDir`.

### Alternatives

We can leave this feature unimplemented.

**Comment by jplatte** [comment]
This seems sufficiently complex to be its own crate.

**Comment by jplatte** [comment]
Additionally, maintenance bandwidth is very limited for tower-http at the moment, which further makes new medium-to-large features very hard to land. I'll close this for now, feel free to link to any tower OpenDAL implementations though or further discuss the topic in general.
