### ISSUE TITLE
Ideas for middlewares and leaf services

### ISSUE THREAD

**Issue by davidpdrsn** [tower-rs/tower-http#46]
These are some middlewares or leaf services I'm thinking could be useful. Feel free to suggest others.

- ~~Serve files in directory and subdirectories. Have to take care regarding security.~~ https://github.com/tower-rs/tower-http/pull/45
- Routing. This one might be too framework-ish but some basic routing between services might be useful.
- Caching. Combined with serving files it might be useful to add [HTTP caching](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching).
- Metrics. At Embark we have a middleware that records high level metrics using https://crates.io/crates/metrics. Would probably require the response classification stuff we're working on in https://github.com/tower-rs/tower-http/pull/40. Also probably shouldn't be hard coded to use the metrics crate.
- Authorization. Basic auth or some kind of customizable "Bearer" auth probably.
- Cookie encryption/decryption.
- Redirect HTTP to HTTPS.
- Health check. Some kind of health check service that is compatible with [k8s](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes).
- Middleware for mapping request and/or response bodies.

Feel free to submit PRs for these.

**Comment by hamza1311** [comment]
Another idea: service to setup serving Single Page Applications.

**Comment by davidpdrsn** [comment]
> Another idea: service to setup serving Single Page Applications.

I don't have experience building SPAs. What needs do they have outside of serving static files?

**Comment by hamza1311** [comment]
> > Another idea: service to setup serving Single Page Applications.
> 
> I don't have experience building SPAs. What needs do they have outside of serving static files?

They require that every unknown route serve the `index.html`, letting the client to handle routing.

One implementation detail for service included: it should have a way ignore routes (so we can have a normal 404 response for, say `/api` routes and serve the SPA for everything else)

**Comment by davidpdrsn** [comment]
My gut feeling is that something like that fits better in its own crate or perhaps built with warp. I’m open to looking at PRs or hearing from others who want something like this though.

**Comment by davidpdrsn** [comment]
It could also be something a potential general routing middleware could support.

**Comment by hamza1311** [comment]
> My gut feeling is that something like that fits better in its own crate or perhaps built with warp.

I have [implemented it in warp](https://github.com/hamza1311/waichu/blob/a221d55d8d05546d94fd3b8557f37306734fbd7f/backend/src/utils/filters.rs#L51-L66) before and the only possible way (that I'm aware of) is by string parsing which isn't the best thing (lack of extensibility, etc).

> It could also be something a potential general routing middleware could support.

I think this goes with the first 2 points mentioned here, static files and routing. If combine both of those, we can expose a nice API for handling SPAs

**Comment by davidpdrsn** [comment]
I have made new issues for each of these so going to close this. If people have ideas for new middlewares they should be opened as separate issues.
