### ISSUE TITLE
Cors not compatibile with axum 0.7.0

### ISSUE THREAD

**Issue by griebdaniel** [tower-rs/tower-http#464]
- [ ] I have looked for existing issues (including closed) about this

### Motivation

Compatibility with axum 0.7.0 regarding to cors functionality

### Proposal

Allow this to work:
let app = Router::new().route("/supply", get(move || get_supplies(pool.clone()))).layer(CorsLayer::permissive());

Currently gives the following error:
the trait bound `Cors<Route>: tower_service::Service<axum::http::Request<Body>>` is not satisfied
the trait `tower_service::Service<http::request::Request<ReqBody>>` is implemented for `Cors<S>`

**Comment by jplatte** [comment]
Which version of tower-http?

**Comment by griebdaniel** [comment]
I'm sorry I used the wrong version of tower-http.

**Comment by lungbean23** [comment]
> I'm sorry I used the wrong version of tower-http.

which version of tower-http did you use? i am failing with :"tower-http = { version = "0.4", features = ["cors"] }". 

praise the jippity

**Comment by lungbean23** [comment]
i fixed mine with 
    axum = "0.8.3"
    tower-http = "0.5.1






hayuken.
