### ISSUE TITLE
CompressionService removes content-length header from Response

### ISSUE THREAD

**Issue by hamza1311** [tower-rs/tower-http#48]
`CompressionService` removes `content-length` header from `Response` instead of replacing it with the length of length of compressed body.

**My code**:
```rust
async fn hello(_: Request<Body>) -> Result<Response<Body>, Infallible> {
    let body = "Hello World!\n".as_bytes().to_vec();
    let body = Body::from(body.clone());
    eprintln!("size {:?}", body.size_hint().exact());
    let mut resp = Response::new(body);
    Ok(resp)
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    pretty_env_logger::init();

    let make_svc = make_service_fn(|_conn| {
        let svc = service_fn(hello);
        async move { Ok::<_, Infallible>(svc) }
    });

    let addr = ([127, 0, 0, 1], 3000).into();

    let server = Server::bind(&addr).serve(make_svc);
    server.await?;

    println!("Listening on http://{}", addr);

    Ok(())
}
```
**Response**:
```console
$ curl -i localhost:3000 --compressed
HTTP/1.1 200 OK
content-encoding: deflate
transfer-encoding: chunked
date: Mon, 01 Feb 2021 16:03:47 GMT

Hello World!
```

Replacing 
```rust
let svc = service_fn(hello);
```
with 
```rust
let svc = ServiceBuilder::new()
    .layer(CompressionLayer::new())
    .service(service_fn(hello));
```
results in
```console
$ curl -i localhost:3000 --compressed
HTTP/1.1 200 OK
content-encoding: deflate
transfer-encoding: chunked
date: Mon, 01 Feb 2021 16:03:47 GMT

Hello World!
```

The header should not be removed, instead it should updated if required.

**Comment by davidpdrsn** [comment]
I’m not sure this is possible to fix. The compression works on a “compress an async stream of bytes” level so there isn’t a way to know the length without buffering the whole stream.

**Comment by hamza1311** [comment]
I see. What do you think of giving user the option to buffer?

**Comment by davidpdrsn** [comment]
Buffering all the data doesn't great, even if an opt-int. Could be gigs and gigs of data.

Whats the use case requiring you to have `Content-Length` present? [Hyper already adds `Transfer-Encoding: chunked`](https://stackoverflow.com/questions/63463680/how-to-send-chunked-transfer-encoded-hyper-response). HTTP doesn't allow both `Content-Length` and `Transfer-Encoding`. I'm not sure what other servers do.

**Comment by hamza1311** [comment]
> HTTP doesn't allow both `Content-Length` and `Transfer-Encoding`. I'm not sure what other servers do.

I did not know that. Thanks for informing me. TIL

**Comment by davidpdrsn** [comment]
Tbh I didn’t know that either until today 😅

**Comment by seanmonstar** [comment]
Granted, hyper adds `chunked` only if a) there isn't a `content-length` header as part of the request, and b) the body's `size_hint()` doesn't have an exact length set. So, if you knew the length after compression, it'd be fine...

**Comment by davidpdrsn** [comment]
@seanmonstar Thanks for the clarification!

I don't know much about compression but I don't suppose there is a way to find the length of the compressed body without buffering the whole thing?

**Comment by seanmonstar** [comment]
No, not usually. Especially since this `Service` is trying to compress a streaming body, I agree with the resolution that there's nothing to do here. A user who wants compression and a length can do it outside this middleware.
