### ISSUE TITLE
Using CorsLayer with axum blocks all http requests OPTIONS method

### ISSUE THREAD

**Issue by daltoncoder** [tower-rs/tower-http#497]
- [ x] I have looked for existing issues (including closed) about this

### Version
tower-http v0.5.2

### Platform

Linux 6.9.3-arch1-1 

### Description

It seems using CorsLayer as a layer on an axum server stops any request with an OPTIONS method from ever hitting handler and responds with a default blank 200 response. Issue happens when using CorsLayer::permissive() and very_permissive(). I once was hitting the issue when manually adding with_methods() but currently can not recreate. Here is minimal snippet of code that will reproduce the bug. If you send any request with OPTIONS method the handler will never get hit.

```rust
use axum::{routing::any, Router};
use tower_http::cors::CorsLayer;

#[tokio::main]
async fn main() {
    let app = Router::new()
        .route("/", any(root))
        .layer(CorsLayer::permissive());

    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();
    axum::serve(listener, app).await.unwrap();
}

async fn root() -> String {
    println!("in the handler");
    "Hello".to_string()
}
```

**Comment by jplatte** [comment]
This is intended, not a bug. The middleware handles `OPTIONS` requests without calling the inner service. Why do you want to write a custom handler for it?

**Comment by georgeboot** [comment]
@jplatte there are valid use cases for implementing a custom options handler. For example. the [allow header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Allow) specifies the allowed http verbs for the route.

In some api standards (for example [OGC API - Schemas](https://docs.ogc.org/DRAFTS/20-002r1.html)) this method is used to indicate what operations (CRUD) are supported on each endpoint. This follows the REST ideology.

I believe the cors options handler should be able to forward the request to a downstream controller, to give the possibility of implementing custom logic.

**Comment by jplatte** [comment]
I would recommend you write your own middleware that wraps the cors middleware, or fork it to support your use case.
