### ISSUE TITLE
Add support for `*` + `Authorization` together in `cors::AllowHeaders`

### ISSUE THREAD

**Issue by ClementNerma** [tower-rs/tower-http#526]
- [x] I have looked for existing issues (including closed) about this

### Motivation

In the future, providing a wildcard (`*`) as the `Accept-Control-Allow-Headers` header's value will still reject the `Authorization` header.

Per [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers):

> The value * only counts as a special wildcard value for requests without credentials (requests without [HTTP cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies) or HTTP authentication information). In requests with credentials, it is treated as the literal header name * without special semantics. Note that the [Authorization](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization) header can't be wildcarded and always needs to be listed explicitly.

### Proposal

This could be implemented in several ways:

1. Make the `.any()` method take a required argument to specify weither to allow the `Authorization` header or not. This is the best implementation as this would avoid footgun and force users to consider if they need this header or not. But this would also be a breaking change. It's still possible to do this thanks to `tower-http` not being stable (as in >= `1.x`) yet.

2. Deprecate the `.any()` method and add the forementioned one under a name like `.any_with_authorization(...)` (name TBD)

3. Add this new method without deprecating `.any()`. This will cause the less disruption but is a bad idea IMO as most people don't expect `.any()` to allow every single header _except_ one, even though this is caused by a web spec and not by the library, it's still a footgun.

### Alternatives

If we want to have programmatic implementation of the `* Headers` value, I don't see any other alternative.

**Comment by jplatte** [comment]
Are you certain that `*, Authorization` is going to do the right thing? The syntax section on MDN makes it look like no.

Also, note that there's already [`AllowHeaders::mirror_request`](https://docs.rs/tower-http/latest/tower_http/cors/struct.AllowHeaders.html#method.mirror_request) (which is what you need to use to allow any header in combination with `AllowCredentials::yes()` / `Access-Control-Allow-Credentials: true`).

**Comment by ClementNerma** [comment]
Note sure about the syntax no, it was just an example. But you're right about `mirror_request`, seems like it should do the trick!
Thanks :)
