### ISSUE TITLE
Compression and Decompression breaks tonic streams

### ISSUE THREAD

**Issue by davidpdrsn** [tower-rs/tower-http#81]
I've noticed using the compression and decompression middlewares makes tonic streaming messages not get delivered for some reason.

Noticed while adding a stream example to the tonic example.

**Comment by davidpdrsn** [comment]
I have spent all day trying to fix this but I cannot find anything 😞 

I have made a [minimal reproducible example](https://github.com/davidpdrsn/minimal-compression-example) in case someone wants to have a go.

I first thought it was due to `is_end_stream` not getting delegated correctly, but that doesn't seem to be the case.

Also, if you compress/decompress things directly in `poll_data` with [flate2](https://docs.rs/flate2/1.0.20/flate2) it does work. Could async-compression be splitting messages in a way that isn't compatible with grpc?

@tesaguri do you have any idea what could be causing this?

**Comment by seanmonstar** [comment]
Doesn't protobuf place compression info in the protobuf binary format? I think there's a flag when decoding that signals that a message is compressed.

**Comment by davidpdrsn** [comment]
Yeah I think it does. Seen mentions of it in the tonic code.

Tower-http's middleware work at the http_body::Body layer so in theory compression should be applied and unapplied transparently before responses reaches the grpc client service. But seems not 😞

**Comment by LucioFranco** [comment]
@davidpdrsn do you think we can implement a `Body` that does it DATA frame by DATA frame instead of over the whole body?

We could probably read the headers than when we create the Body middleware to decompress we can teach it how to read grpc? but maybe this is getting to the point where it makes sense to add this into tonic itself.

**Comment by davidpdrsn** [comment]
> do you think we can implement a Body that does it DATA frame by DATA frame instead of over the whole body?

@LucioFranco Yep totally. I actually did that during my testing and that does work. You can even do it with something like [flate2](https://crates.io/crates/flate2) as you don't need async compression.

That is a direction I want to explore in the future but probably not necessary for the first version of this. Might also require some additional like for things like "should users be able to choose between whole body or single frame compression regardless of gRPC or not" kinda questions.
